INSERT INTO CmsConfeitaria..Ingrediente(nome, dataCadastro) VALUES ('Fubá', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Morango', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Banana', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Limão',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Fermento em pó', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Fermento seco',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Fubá',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Creme de Leite', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Leite', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Doce de Leite', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Chantily', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Açucar Real', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Queijo Minas meio curado', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Canela', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Glanulado de chocolate', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Chocolate em pó', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Cobertura de Chocolate', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Amarula', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Cachaça', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Coco Ralado', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Baunilha', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Essênica de panetone', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Gelarina em pó de abacaxi', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Gelarina em pó de morango', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Gelarina em pó de uva', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Gelarina em folha', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Ovo', getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Farinha de trigo',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Margarina',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Mantega',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Cream Cheese',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Ricota',  getDate());
INSERT INTO Ingrediente(nome, dataCadastro) VALUES ('Achocolatado',  getDate());


